/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blokus.controller;

import static org.testng.Assert.assertNotNull;

import org.testng.annotations.Test;

import blokus.model.PlayerType;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        Game game = new Game();
        game.addPlayer(PlayerType.RANDOM);
        assertNotNull(game.getCurPlayer(), "current player should be set");
    }
}
